import {
  meta,
  shopify,
  starbucks,
  tesla,
  algeriapartners,
  algposte,
  ooredoo,
  mfg,
  gica,
} from "../assets/images";
import {
  car,
  contact,
  css,
  estate,
  express,
  git,
  github,
  html,
  javascript,
  linkedin,
  mongodb,
  motion,
  mui,
  nextjs,
  nodejs,
  pricewise,
  react,
  redux,
  sass,
  snapgram,
  summiz,
  tailwindcss,
  threads,
  typescript,
} from "../assets/icons";

export const skills = [
  {
    imageUrl: css,
    name: "CSS",
    type: "Frontend",
  },
  {
    imageUrl: git,
    name: "Git",
    type: "Version Control",
  },
  {
    imageUrl: github,
    name: "GitHub",
    type: "Version Control",
  },
  {
    imageUrl: html,
    name: "HTML",
    type: "Frontend",
  },
  {
    imageUrl: javascript,
    name: "JavaScript",
    type: "Frontend",
  },
  {
    imageUrl: mongodb,
    name: "MongoDB",
    type: "Database",
  },
  {
    imageUrl: mui,
    name: "Material-UI",
    type: "Frontend",
  },
  {
    imageUrl: nextjs,
    name: "Next.js",
    type: "Frontend",
  },
  {
    imageUrl: nodejs,
    name: "Node.js",
    type: "Backend",
  },
  {
    imageUrl: react,
    name: "React",
    type: "Frontend",
  },
  {
    imageUrl: redux,
    name: "Redux",
    type: "State Management",
  },
  {
    imageUrl: tailwindcss,
    name: "Tailwind CSS",
    type: "Frontend",
  },
  {
    imageUrl: typescript,
    name: "TypeScript",
    type: "Frontend",
  },
];

export const experiences = [
  {
    title: "Mobile Developer",
    company_name: "Ooredoo",
    icon: ooredoo,
    iconBg: "#fbc3bc",
    date: "Feb 2016 - May 2016",
    points: [
      "Developing android Application using Android SDK and other related technologies.",
      "Collaborating with cross-functional teams including database designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Web Developer",
    company_name: "Algerie Poste",
    icon: algposte,
    iconBg: "#accbe1",
    date: "Feb 2020 - Jul 2020",
    points: [
      "Creating Projects Management Web Application in Java & Spring Boot.",
      "Intended for Managers to manage their projects.",
      "Its function is similar to Microsoft's MS Project and Trello.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Software Developer",
    company_name: "Mediterranean Float Glass MFG",
    icon: mfg,
    iconBg: "#b7e4c7",
    date: "Sep 2021 - Dec 2021",
    points: [
      "Developing a Desktop software using C Sharp & SpreadshetGear.",
      "It's for organizing their Unclear Excel files.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "The unclear files are generated by an old electronic software linked with a glass machine.",
    ],
  },
  {
    title: "Database Modeleer",
    company_name: "ALGERIA PARTNERS",
    icon: algeriapartners,
    iconBg: "brown",
    date: "Apr 2023 - Jul 2023",
    points: [
      "Designing a Relational Database using MERISE Methodology.",
      "Participant in DB Designers team & collaborating with cross-functional teams including Front/Back end developers to create high-quality WebSite.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "It's for a Global Algeria Digital Market site driven by ALGERIA PARTNERS.",
    ],
  },
  {
    title: "Full stack Developer",
    company_name: "SMIF groupe GICA",
    icon: gica,
    iconBg: "#a2d2ff",
    date: "Mars 2023 - Oct 2023",
    points: [
      "Developing web application using React.js and other related technologies.",
      "Learning to handle with reports visualized with charts.",
      "Implementing responsive design charts and ensuring cross-browser compatibility.",
      "Learning with great practise Syncfusion React UI Library, good experience using third party.",
    ],
  },
];

export const socialLinks = [
  {
    name: "Contact",
    iconUrl: contact,
    link: "/contact",
  },
  {
    name: "GitHub",
    iconUrl: github,
    link: "https://github.com/YourGitHubUsername",
  },
  {
    name: "LinkedIn",
    iconUrl: linkedin,
    link: "https://www.linkedin.com/in/YourLinkedInUsername",
  },
];

export const projects = [
  {
    iconUrl: pricewise,
    theme: "btn-back-red",
    name: "Scout Chat",
    description:
      "Developed a web application that tracks and notifies users of price changes for products on Amazon, helping users find the best deals.",
    link: "https://github.com/coderZkr/3DPortFolio/",
  },
  {
    iconUrl: threads,
    theme: "btn-back-green",
    name: "Full Stack Trello Clone",
    description:
      'Created a full-stack replica of the popular discussion platform "Threads," enabling users to post and engage in threaded conversations.',
    link: "https://github.com/coderZkr/3DPortFolio/",
  },
  {
    iconUrl: car,
    theme: "btn-back-blue",
    name: "Scout Chat App",
    description:
      "Designed and built a mobile app for chatting and hikes notificating on the market, streamlining the car-buying process.",
    link: "https://github.com/coderZkr/3DPortFolio/",
  },
  {
    iconUrl: snapgram,
    theme: "btn-back-pink",
    name: "Full Stack Instagram Clone",
    description:
      "Built a complete clone of Instagram, allowing users to share photos and connect with friends in a familiar social media environment.",
    link: "https://github.com/coderZkr/3DPortFolio/",
  },
  {
    iconUrl: estate,
    theme: "btn-back-black",
    name: "Real-Estate Application",
    description:
      "Developed a web application for real estate listings, facilitating property searches and connecting buyers with sellers.",
    link: "https://github.com/coderZkr/3DPortFolio/",
  },
  {
    iconUrl: summiz,
    theme: "btn-back-yellow",
    name: "AI Summarizer Application",
    description:
      "App that leverages AI to automatically generate concise & informative summaries from lengthy text content, or blogs.",
    link: "https://github.com/coderZkr/3DPortFolio/",
  },
];
